version: '3.9'

services:

  backend:
    image: yananas23/giftlist-backend:latest
    container_name: giftlist_backend
    env_file:
      - ./backend.env
    ports:
      - "8117:8117" # expos√© pour debug, mais nginx s'y connecte en interne
    networks:
      - gift-network

  frontend:
    image: yananas23/giftlist-frontend:latest
    container_name: giftlist_frontend
    networks:
      - gift-network

  nginx:
    image: nginx:latest
    container_name: giftlist_nginx
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/storybook:/usr/share/nginx/storybook:ro
    depends_on:
      - frontend
      - backend
    networks:
      - gift-network

networks:
  gift-network:
    driver: bridge
